#!/bin/sh

current_time=$(date "+%Y%m%d%H%M%S")

ssh -T deploy@dcdlrhr902 <<EOF
  cd /var/www/neuroshare-dev-integration/releases
  git clone -b development-deploy git@github.com:SutterRDD/neuro-share-app.git $current_time
  cd $current_time
  ln -sf /var/www/neuroshare-dev-integration/shared/config/environment.ts src/environments/environment.ts
  ln -sf /var/www/neuroshare-dev-integration/shared/config/options.js src/assets/options.js
  npm install
  ng build
  pm2 stop neuroSHARE-dev-integration
  rm /var/www/neuroshare-dev-integration/current
  ln -s /var/www/neuroshare-dev-integration/releases/$current_time /var/www/neuroshare-dev-integration/current
  pm2 start /var/www/neuroshare-dev-integration/shared/config/pm2.json
  cd /var/www/neuroshare-dev-integration/releases && ls -t1 | tail -n +4 | xargs rm -r
  exit
EOF
