#!/bin/sh

current_time=$(date "+%Y%m%d%H%M%S")

ssh -T deploy@dcplrhr102 <<EOF
  cd /var/www/neuroshare/releases
  git clone -b master git@github.com:SutterRDD/neuro-share-app.git $current_time
  cd $current_time
  ln -sf /var/www/neuroshare/shared/config/environment.ts src/environments/environment.ts
  ln -sf /var/www/neuroshare/shared/config/options.js src/assets/options.js
  npm install
  ng build
  pm2 stop neuroSHARE
  rm /var/www/neuroshare/current
  ln -s /var/www/neuroshare/releases/$current_time /var/www/neuroshare/current
  pm2 start /var/www/neuroshare/shared/config/pm2.json
  cd /var/www/neuroshare/releases && ls -t1 | tail -n +4 | xargs rm -r
  exit
EOF